name: build

on:
  push:
    paths:
      - "public/manifest.json"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: borales/actions-yarn@v2.3.0
      with:
          cmd: install # will run `yarn install` command

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
    
    - name: "Package the extension"
      run: |
          zip -r nyaa-util.zip dist
    
    - name: Create pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "pre-release"
        prerelease: true
        title: "Pre-release Build (rewrite W.I.P.)"
        files: |
          nyaa-util.zip
